### ISSUE TITLE
Cold chain: Add section titles in configuration modal

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/notify#111]
## Is your feature request related to a problem? Please describe

It would be good to add titles to sections of the configuration modal to make it easier for the user to understand.

## Describe the solution you'd like

See green highlights: 

<img width="1523" alt="image" src="https://github.com/openmsupply/notify/assets/19318937/1e22103f-06c7-4f45-91c8-47ba536233a8">

**Comment by adamdewey** [comment]
Hey @jmbrunskill and @Mai21 - I see #131 says that is closes this issue, but actually there were a few more rearrangements and section headers (highlighted in green in the screenshot)

Would it be possible to do those too before closing this issue?

Cheers!

**Comment by Mai21** [comment]
@adamdewey We changed Set up CC UI from the modal to the page. And recipients are now under the title.
Do we still need to add the section headers for recipients?
I'll add Preference header and send confirmation message when alert is resolved, fixed the title "Select Locations" to "Stoes and Locations".
![Screenshot 2023-10-02 at 11 49 05 AM](https://github.com/openmsupply/notify/assets/36495540/1740b72f-48b6-4937-99bd-f418d042e2af)

**Comment by adamdewey** [comment]
@Mai21 - nice!

I think it would be good to add the recipients title too, just so it's obvious it's another configuration section - it can stay at the top though, all good!
