### ISSUE TITLE
Notification is saved when the notification edit window is closed without saving

### ISSUE THREAD

**Issue by Mai21** [openmsupply/notify#144]
## Describe the bug

Notification is saved when the notification edit window is closed without saving

https://github.com/openmsupply/notify/assets/36495540/b4ecd9d1-33d3-419b-afcd-2ef6f39437d1

## To Reproduce

Steps to reproduce the behaviour:

1. Go to Notifications 
2. Click on 'New Notification'
3. Select 'Scheduled' and input the name of notification, Click on 'Create'
4. Click on 'Close' without saving
5. In the list, the new notification is added

## Expected behaviour

Before saving, it shouldn't be saved

**Comment by jmbrunskill** [comment]
I'm ok with this behaviour, it makes the code much easier as we get the id as soon as we use the create modal.
There's similar behaviour in open-mSupply, you create a requisition (essentially as blank) then you can edit it...
What do you think?

**Comment by Mai21** [comment]
@jmbrunskill Ah, okay, if it's an expected behaviour, it will be no problem! We can close this issue.

**Comment by jmbrunskill** [comment]
Expected behaviour
