### ISSUE TITLE
Cold Chain Notification Configuration should show the 'real' locations/stores

### ISSUE THREAD

**Issue by jmbrunskill** [openmsupply/notify#165]
## Is your feature request related to a problem? Please describe

Right now a hard coded list of locations with sensors is shown in the configuration.

## Describe the solution you'd like

The mSupply Locations containing sensors should be shown and be available to configure.

## Acceptance Criteria

- [ ] The list of all active sensors configured in mSupply is displayed
- [ ] Saving the list of sensor works (able to save the list and reopen with the same list showing up)
- [ ] If sensor query fails (e.g. not connected to dashboard DB) an error should show
- [ ] Without a location, the notification shouldn't be able to be saved as `enabled`

**Comment by adamdewey** [comment]
@jmbrunskill Be great to perhaps capture sensors instead of Locations for MVP as not all Stores use Locations at the moment so might need a bit more thought about how to handle that?

**Comment by jmbrunskill** [comment]
> @jmbrunskill Be great to perhaps capture sensors instead of Locations for MVP as not all Stores use Locations at the moment so might need a bit more thought about how to handle that?

As discussed updated this to be a sensor selection modal
