### ISSUE TITLE
Allow scheduled reports to loop over an array of parameters

### ISSUE THREAD

**Issue by jmbrunskill** [openmsupply/notify#194]
## Is your feature request related to a problem? Please describe

Scheduled reports currently only have one set of parameters. I should be possible to setup a report with an array of parameters which are looped overs.
## Describe the solution you'd like

If the parameters for a scheduled configuration are an array, the scheduled config should be able to run more than once for each set of paramters.

E.g. if you have a parameter called `Store` for your configuration, if you have an array of Stores, each store will be evaluated separately as though you had duplicated the configuration for each store.

## Acceptance Criteria

- [ ] Able to configure an array of parameters for 
- [ ] Optional fast way to configure e.g. copy and paste in a json array

**Comment by mark-prins** [comment]
> the scheduled config should be able to run more than once for each set of parameters

This is slightly ambiguous, so just to check: the report should be able to run more than once. The report will run _once_ for each set of parameters which has been defined.

**Comment by jmbrunskill** [comment]
> > the scheduled config should be able to run more than once for each set of parameters
> 
> This is slightly ambiguous, so just to check: the report should be able to run more than once. The report will run _once_ for each set of parameters which has been defined.

Correct! Sorry for the ambiguity
