### ISSUE TITLE
Add recipient/list IDs to notification config

### ISSUE THREAD

**Issue by lache-melvin** [openmsupply/notify#72]
## Is your feature request related to a problem? Please describe

Currently, we are storing the recipient ids and recipient list ids for notification configs in the `configuration_data`. However, as every notification config will have these fields, it should be on the base NotificationConfig.

## Describe the solution you'd like

These should probably be two new join tables (notification_config_recipient & notification_config_recipient_list). They could then be added to the `NotificationConfigNode` via loaders in the graphql layer for the frontend.

## Describe alternatives you've considered

Originally we thought to simply have `recipientIds` and `recipientListIds` as fields on the NotificationConfig, but this is a bit brittle (i.e. if a recipient is deleted, or what if we want to see that the notifications a recipient is subscribed to?) The join seems more robust/flexible.

**Comment by jmbrunskill** [comment]
Done as part of #138
